name: tradeshow
description: Trade show game for Magento Imagine.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^3.1.0
  #equatable: ^0.4.0
  equatable: ^1.1.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.4+8
  shared_preferences_web: ^0.1.0
  # Cloud firestore web
  cloud_firestore: ^0.13.2
  # Email validator
  email_validator: ^1.0.0
  # MobX
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2
  # Provider
  provider: ^4.0.4
  # Network state
  network_state: ^0.0.1
  #Auto size text
  auto_size_text: ^2.1.0
  #Icons
  material_design_icons_flutter: ^3.4.4995

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2

flutter:
  fonts:
    - family: Varela Round
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
  uses-material-design: true
